export type SceneType = "chapter" | "image" | "portrait" | "depth" | "video" | "quote" | "timeline" | "comparison" | "statistic" | "chart" | "map" | "document" | "relationship" | "montage";
export type SceneContent = {
  type?: SceneType;
  title?: string;
  subtitle?: string;
  image?: string;
  imagePosition?: string;
  panX?: number;
  panY?: number;
  zoomFrom?: number;
  zoomTo?: number;
  quote?: string;
  attribution?: string;
  events?: Array<{label: string; detail: string}>;
  left?: {label: string; detail: string};
  right?: {label: string; detail: string};
  value?: string;
  label?: string;
  items?: Array<{label: string; value: number; detail?: string}>;
  points?: Array<{label: string; x: number; y: number}>;
  documentText?: string;
  relations?: Array<{from: string; to: string; label?: string}>;
  images?: string[];
  video?: string;
  videoFit?: "cover" | "contain";
  videoStartInFrames?: number;
  videoPlaybackRate?: number;
  videoMuted?: boolean;
  videoVolume?: number;
  layers?: Array<{assetId?: string; image?: string; video?: string; depth?: number; x?: number; y?: number; scale?: number; opacity?: number; mask?: string}>;
};
export type Scene = {id: string; startFrame: number; endFrame: number; durationInFrames: number; timingSource: string; assetIds?: string[]; content?: SceneContent};
export type Caption = {id: string; sceneId: string; startFrame: number; endFrame: number; text: string};
export type RemotionEffect = {id: string; sceneId: string; type: string; label: string; startFrame: number; endFrame: number; parameters?: Record<string, unknown>};
export type Asset = {id: string; groupId?: string; sceneId: string | null; kind: "image" | "video"; selected: boolean; provider?: string; path: string; url: string};
export type Stage = {id: string; label: string; kind?: string; path: string; exists: boolean; url: string | null};
export type Model = {id: string; label: string; provider: string; capabilities: string[]; modalities?: {input: string[]; output: string[]}; contextWindow?: number; status?: string};
export type ModelCatalog = {image: Model[]; voice: Model[]};
export type Cover = {assetId: string; sceneId: string | null; path: string; selectedAt: string};
export type AudioTrack = {id: string; label: string; path: string; exists: boolean; url: string | null};
export type ProjectAudio = {voiceover: AudioTrack; music: AudioTrack; sfx: AudioTrack[]};
export type GenerationKind = "images" | "video" | "voiceover" | "music";
export type GenerationJob = {id: string; videoId: string; kind: GenerationKind; status: "queued" | "running" | "succeeded" | "failed"; createdAt: string; startedAt?: string; completedAt?: string; error?: string};
export type RenderKind = "still" | "preview" | "final";
export type RenderJob = {id: string; videoId: string; kind: RenderKind; status: "queued" | "running" | "succeeded" | "failed"; createdAt: string; startedAt?: string; completedAt?: string; error?: string};
export type QaKind = "video" | "images" | "generated-videos";
export type QaJob = {id: string; videoId: string; kind: QaKind; status: "queued" | "running" | "succeeded" | "failed"; createdAt: string; startedAt?: string; completedAt?: string; error?: string};
export type QaSummary = {passed: boolean; reports?: Array<{kind: QaKind; passed: boolean; checkedAt?: string}>};
export type SourceBlock = {id: string; locator: string; text: string};
export type ProjectSource = {id: string; title: string; type: string; origin: string; rights: string; sha256: string; blocks: SourceBlock[]};
export type SourceIndex = {videoId: string; sources: ProjectSource[]};
export type SourceCatalog = {videoId: string; entities: Array<Record<string, unknown>>; quotations: Array<Record<string, unknown>>; claims: Array<Record<string, unknown>>; illustrations: Array<Record<string, unknown>>};
export type SourceJob = {id: string; videoId: string; status: "queued" | "running" | "succeeded" | "failed"; createdAt: string; startedAt?: string; completedAt?: string; error?: string};
export type TimingJob = {id: string; videoId: string; status: "queued" | "running" | "succeeded" | "failed"; createdAt: string; startedAt?: string; completedAt?: string; error?: string};
export type GenerationReadiness = {videoId: string; passed: boolean; errors: string[]; warnings: string[]; plan: {present: boolean; valid: boolean}; script: {present: boolean; valid: boolean; segments: number}; generation: {imageModel: string | null; voiceModel: string | null; imageAssets: number; assignedScenes: string[]}; timing: {planPresent: boolean; voiceManifestPresent: boolean}};
export type StoryboardArtifact = {videoId: string; path: string; content: string};
export type GenerationPreparation = {videoId: string; path: string; imageModel: string | null; assetCount: number; preparedSceneIds: string[]};
export type SourceUpload = {videoId: string; source: {id: string; title: string; type: string; input: string; rights: string}};
export type VideoPlanScene = {id: string; chapterId: string; title: string; type: SceneType; objective: string; sourceBlockIds: string[]; visualDirection?: string};
export type VideoPlanChapter = {id: string; title: string; objective: string; sourceBlockIds: string[]; sceneIds: string[]};
export type VideoPlan = {version: 1; title: string; adaptationMode: "overview" | "chapter-explanation" | "documentary" | "series-episode"; audience: string; language: string; durationSeconds: number; sourceBlockIds: string[]; chapters: VideoPlanChapter[]; scenes: VideoPlanScene[]};
export type ProjectState = {videoId: string; composition: {fps: number; durationInFrames: number; width: number; height: number}; models: {image: string | null; voice: string | null}; registry: {image: Model[]; voice: Model[]}; scenes: Scene[]; captions: Caption[]; effects: RemotionEffect[]; audio: ProjectAudio; cover: Cover | null; assets: Asset[]; stages: Stage[]; revisions: Array<{id: string; assetId: string; instruction: string; status: string}>; sources: ProjectSource[]; plan: VideoPlan | null; qa: QaSummary | null};

export interface ProjectTransport {
  listProjects(): Promise<string[]>;
  listModels(): Promise<ModelCatalog>;
  getProject(videoId: string): Promise<ProjectState>;
  updateCaption(videoId: string, caption: Caption): Promise<void>;
  updateTimelineRange(videoId: string, input: {type: 'scene' | 'caption' | 'voice' | 'effect' | 'music'; id: string; startFrame: number; endFrame: number}): Promise<void>;
  updateModels(videoId: string, models: {image?: string; voice?: string}): Promise<void>;
  generate(videoId: string, kind: GenerationKind, force?: boolean): Promise<GenerationJob>;
  getGenerationJob(jobId: string): Promise<GenerationJob>;
  render(videoId: string, kind: RenderKind, force?: boolean): Promise<RenderJob>;
  getRenderJob(jobId: string): Promise<RenderJob>;
  runQa(videoId: string, kind: QaKind): Promise<QaJob>;
  getQaJob(jobId: string): Promise<QaJob>;
  uploadSource(videoId: string, file: Blob & {name: string}): Promise<SourceUpload>;
  ingestSources(videoId: string, force?: boolean): Promise<SourceJob>;
  getSourceJob(jobId: string): Promise<SourceJob>;
  buildTiming(videoId: string, force?: boolean): Promise<TimingJob>;
  getTimingJob(jobId: string): Promise<TimingJob>;
  checkGenerationReadiness(videoId: string): Promise<GenerationReadiness>;
  buildStoryboard(videoId: string, force?: boolean): Promise<StoryboardArtifact>;
  prepareGeneration(videoId: string): Promise<GenerationPreparation>;
  getSources(videoId: string): Promise<SourceIndex>;
  buildSourceCatalog(videoId: string, force?: boolean): Promise<SourceCatalog>;
  getPlan(videoId: string): Promise<VideoPlan | null>;
  savePlan(videoId: string, plan: VideoPlan): Promise<VideoPlan>;
  createAssetRevision(videoId: string, input: {assetId: string; sceneId: string | null; modelId: string | null; instruction: string}): Promise<void>;
  setCover(videoId: string, assetId: string): Promise<void>;
}
