export type SceneType = "chapter" | "image" | "portrait" | "depth" | "video" | "quote" | "timeline" | "comparison" | "statistic" | "chart" | "map" | "document" | "relationship" | "montage";
export type SceneContent = {
  type?: SceneType;
  title?: string;
  subtitle?: string;
  image?: string;
  imagePosition?: string;
  panX?: number;
  panY?: number;
  zoomFrom?: number;
  zoomTo?: number;
  quote?: string;
  attribution?: string;
  events?: Array<{label: string; detail: string}>;
  left?: {label: string; detail: string};
  right?: {label: string; detail: string};
  value?: string;
  label?: string;
  items?: Array<{label: string; value: number; detail?: string}>;
  points?: Array<{label: string; x: number; y: number}>;
  documentText?: string;
  relations?: Array<{from: string; to: string; label?: string}>;
  images?: string[];
  video?: string;
  videoFit?: "cover" | "contain";
  videoStartInFrames?: number;
  videoPlaybackRate?: number;
  videoMuted?: boolean;
  videoVolume?: number;
  layers?: Array<{assetId?: string; image?: string; video?: string; depth?: number; x?: number; y?: number; scale?: number; opacity?: number; mask?: string}>;
};
export type Scene = {id: string; startFrame: number; endFrame: number; durationInFrames: number; timingSource: string; assetIds?: string[]; content?: SceneContent};
export type Caption = {id: string; sceneId: string; startFrame: number; endFrame: number; text: string};
export type RemotionEffect = {id: string; sceneId: string; type: string; label: string; startFrame: number; endFrame: number; parameters?: Record<string, unknown>};
export type Asset = {id: string; groupId?: string; sceneId: string | null; kind: "image" | "video"; selected: boolean; provider?: string; path: string; url: string};
export type Stage = {id: string; label: string; kind?: string; path: string; exists: boolean; url: string | null};
export type Model = {id: string; label: string; provider: string; capabilities: string[]; modalities?: {input: string[]; output: string[]}; contextWindow?: number; status?: string};
export type ModelCatalog = {image: Model[]; voice: Model[]};
export type Cover = {assetId: string; sceneId: string | null; path: string; selectedAt: string};
export type AudioTrack = {id: string; label: string; path: string; exists: boolean; url: string | null};
export type ProjectAudio = {voiceover: AudioTrack; music: AudioTrack; sfx: AudioTrack[]};
export type ProjectState = {videoId: string; composition: {fps: number; durationInFrames: number; width: number; height: number}; models: {image: string | null; voice: string | null}; registry: {image: Model[]; voice: Model[]}; scenes: Scene[]; captions: Caption[]; effects: RemotionEffect[]; audio: ProjectAudio; cover: Cover | null; assets: Asset[]; stages: Stage[]; revisions: Array<{id: string; assetId: string; instruction: string; status: string}>; qa: {passed: boolean} | null};

export interface ProjectTransport {
  listProjects(): Promise<string[]>;
  listModels(): Promise<ModelCatalog>;
  getProject(videoId: string): Promise<ProjectState>;
  updateCaption(videoId: string, caption: Caption): Promise<void>;
  updateTimelineRange(videoId: string, input: {type: 'scene' | 'caption' | 'voice' | 'effect' | 'music'; id: string; startFrame: number; endFrame: number}): Promise<void>;
  updateModels(videoId: string, models: {image?: string; voice?: string}): Promise<void>;
  createAssetRevision(videoId: string, input: {assetId: string; sceneId: string | null; modelId: string | null; instruction: string}): Promise<void>;
  setCover(videoId: string, assetId: string): Promise<void>;
}
